version: "3.3"
services:
  #event_ui:
    #build: ui/event
    #depends_on:
      #- event_app  
    #ports:
      #- "8080:8080"

  #event_app:
    #build: app/event
    #ports:
      #- "8090:8090"

  book_ui:
    build: ui/book
    depends_on:
      - book_app
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"

  book_app:
    build: app/book
    ports:
      - "5000:5000"





